# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

renderSqlInternal <- function(sql, parameters) {
    .Call('SqlRender_renderSqlInternal', PACKAGE = 'SqlRender', sql, parameters)
}

translateSqlInternal <- function(sql, replacementPatterns) {
    .Call('SqlRender_translateSqlInternal', PACKAGE = 'SqlRender', sql, replacementPatterns)
}

#' @title splitSql
#'
#' @description
#' \code{splitSql} splits a string containing multiple SQL statements into a vector of SQL statements
#'
#' @details
#' This function is needed because some DBMSs (like ORACLE) do not accepts multiple SQL statements being sent as one execution.
#'
#' @param sql               The SQL string to split into separate statements
#' @return
#' A vector of strings, one for each SQL statement
#' @examples
#' splitSql("SELECT * INTO a FROM b; USE x; DROP TABLE c;")
#'
#' @export
splitSql <- function(sql) {
    .Call('SqlRender_splitSql', PACKAGE = 'SqlRender', sql)
}

